### ISSUE TITLE
any way to highlight selected option

### ISSUE THREAD

**Issue by zinwalin** [aliyigitbireroglu/flutter-cupertino-tabbar#1]
![image](https://user-images.githubusercontent.com/5416196/88869916-9eae7b00-d246-11ea-8672-28a7f59647ff.png)

thanks.

**Comment by aliyigitbireroglu** [comment]
Do you mean changing the text style?

**Comment by zinwalin** [comment]
> Do you mean changing the text style?

exactly.

**Comment by aliyigitbireroglu** [comment]
There should be an example of how to do that in the example project.
