### ISSUE TITLE
Support RTL

### ISSUE THREAD

**Issue by omidraha** [aliyigitbireroglu/flutter-cupertino-tabbar#6]
Currently in `RTL` mode the menu selection and its animation works wrong.

**Comment by omidraha** [comment]
It's related to this [line](https://github.com/aliyigitbireroglu/flutter-cupertino-tabbar/blob/476dc43cc1d2dc65cc9ddc113ff05fa18ff90077/cupertino_tabbar/lib/cupertino_tabbar.dart#L158):


```dart
Alignment get _alignment => Alignment(-1.0 + widget._valueGetter() / (widget._widgets.length - 1) * 2, 0.0);
```

It will be fixed by multiply by minus one when we are in `RTL` mode:
```dart
Alignment get _alignment => Alignment(-1 * (-1.0 + widget._valueGetter() / (widget._widgets.length - 1) * 2), 0.0);
```

**Comment by omidraha** [comment]
I made a [PR](https://github.com/aliyigitbireroglu/flutter-cupertino-tabbar/pull/7).

**Comment by aliyigitbireroglu** [comment]
I merged the PR, thank you.
